# Generated by Django 4.2.7 on 2024-01-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarysecond',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
