# Generated by Django 4.2.7 on 2024-01-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_temporarysecond_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslotsecond',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='timeslotsecond',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
